#!/bin/sh
REAL=`python -c 'import os,sys;print os.path.realpath(sys.argv[1])' "$0"`
DIR=`dirname "$REAL"`/

# active the vitualenv
. "$DIR"/venv/venv-py3/bin/activate

# pass parameter to main script
python "$DIR"/bin/ABLIRC.py "$@"