install.packages("ggplot2",repos="http://cloud.r-project.org/")
install.packages("reshape2",repos="http://cloud.r-project.org/")
install.packages("plotrix",repos="http://cloud.r-project.org/")
install.packages("methods",repos="http://cloud.r-project.org/")
install.packages("corrplot",repos="http://cloud.r-project.org/")
install.packages("RColorBrewer",repos="http://cloud.r-project.org/")
install.packages("Gtable",repos="http://cloud.r-project.org/")
install.packages("Grid",repos="http://cloud.r-project.org/")
